# 機器學習百日馬拉松 Day2

下載Home Credit Default Risk專案的資料集，並透過HomeCredit_columns_description.csv，了解application.csv各欄位的定義

這筆資料的欄位包括：借貸編號、預測是否還款、借貸類別、客戶性別、是否有車有房有小孩、年收入、信用額度等等客戶的資料

評估標準是target欄位，希望能夠透過這樣子的資料，訓練一套模型預測什麼類型的客戶能夠還款，讓借貸的銀行判斷是否要貸款給客戶

使用其中一個資料集application_train.csv做EDA

這份資料集是結構化的資料，資料為數值型和類別型，每一筆資料代表一次借貸的紀錄

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
appdata = pd.read_csv('/Users/eddie/Documents/GitHub/2nd-ML100Days/homework/data-Part01/application_train.csv')
appdata.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
#簡單觀察這個資料集有幾欄、幾列
appdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB

In [7]:
#各欄位的統計
appdata.describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
count,307511.000000,307511.000000,307511.000000,3.075110e+05,3.075110e+05,307499.000000,3.072330e+05,307511.000000,307511.000000,307511.000000,...,307511.000000,307511.000000,307511.000000,307511.000000,265992.000000,265992.000000,265992.000000,265992.000000,265992.000000,265992.000000
mean,278180.518577,0.080729,0.417052,1.687979e+05,5.990260e+05,27108.573909,5.383962e+05,0.020868,-16036.995067,63815.045904,...,0.008130,0.000595,0.000507,0.000335,0.006402,0.007000,0.034362,0.267395,0.265474,1.899974
std,102790.175348,0.272419,0.722121,2.371231e+05,4.024908e+05,14493.737315,3.694465e+05,0.013831,4363.988632,141275.766519,...,0.089798,0.024387,0.022518,0.018299,0.083849,0.110757,0.204685,0.916002,0.794056,1.869295
min,100002.000000,0.000000,0.000000,2.565000e+04,4.500000e+04,1615.500000,4.050000e+04,0.000290,-25229.000000,-17912.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,189145.500000,0.000000,0.000000,1.125000e+05,2.700000e+05,16524.000000,2.385000e+05,0.010006,-19682.000000,-2760.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,278202.000000,0.000000,0.000000,1.471500e+05,5.135310e+05,24903.000000,4.500000e+05,0.018850,-15750.000000,-1213.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,367142.500000,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,0.028663,-12413.000000,-289.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
max,456255.000000,1.000000,19.000000,1.170000e+08,4.050000e+06,258025.500000,4.050000e+06,0.072508,-7489.000000,365243.000000,...,1.000000,1.000000,1.000000,1.000000,4.000000,9.000000,8.000000,27.000000,261.000000,25.000000

In [15]:
#檢查有沒有遺失值，看每個欄位有多少資料，就能知道有多少遺失值
lack = appdata.isnull()
lack_col = lack.any()
print(lack_col)
datanum = appdata.count()
print(datanum)

SK_ID_CURR                    False
TARGET                        False
NAME_CONTRACT_TYPE            False
CODE_GENDER                   False
FLAG_OWN_CAR                  False
FLAG_OWN_REALTY               False
CNT_CHILDREN                  False
AMT_INCOME_TOTAL              False
AMT_CREDIT                    False
AMT_ANNUITY                    True
AMT_GOODS_PRICE                True
NAME_TYPE_SUITE                True
NAME_INCOME_TYPE              False
NAME_EDUCATION_TYPE           False
NAME_FAMILY_STATUS            False
NAME_HOUSING_TYPE             False
REGION_POPULATION_RELATIVE    False
DAYS_BIRTH                    False
DAYS_EMPLOYED                 False
DAYS_REGISTRATION             False
DAYS_ID_PUBLISH               False
OWN_CAR_AGE                    True
FLAG_MOBIL                    False
FLAG_EMP_PHONE                False
FLAG_WORK_PHONE               False
FLAG_CONT_MOBILE              False
FLAG_PHONE                    False
FLAG_EMAIL                    False
OCCUPATION_TYPE                True
CNT_FAM_MEMBERS                True
                              ...
DEF_30_CNT_SOCIAL_CIRCLE       True
OBS_60_CNT_SOCIAL_CIRCLE       True
DEF_60_CNT_SOCIAL_CIRCLE       True
DAYS_LAST_PHONE_CHANGE         True
FLAG_DOCUMENT_2               False
FLAG_DOCUMENT_3               False
FLAG_DOCUMENT_4               False
FLAG_DOCUMENT_5               False
FLAG_DOCUMENT_6               False
FLAG_DOCUMENT_7               False
FLAG_DOCUMENT_8               False
FLAG_DOCUMENT_9               False
FLAG_DOCUMENT_10              False
FLAG_DOCUMENT_11              False
FLAG_DOCUMENT_12              False
FLAG_DOCUMENT_13              False
FLAG_DOCUMENT_14              False
FLAG_DOCUMENT_15              False
FLAG_DOCUMENT_16              False
FLAG_DOCUMENT_17              False
FLAG_DOCUMENT_18              False
FLAG_DOCUMENT_19              False
FLAG_DOCUMENT_20              False
FLAG_DOCUMENT_21              False
AMT_REQ_CREDIT_BUREAU_HOUR     True
AMT_REQ_CREDIT_BUREAU_DAY      True
AMT_REQ_CREDIT_BUREAU_WEEK     True
AMT_REQ_CREDIT_BUREAU_MON      True
AMT_REQ_CREDIT_BUREAU_QRT      True
AMT_REQ_CREDIT_BUREAU_YEAR     True
Length: 122, dtype: bool
SK_ID_CURR                    307511
TARGET                        307511
NAME_CONTRACT_TYPE            307511
CODE_GENDER                   307511
FLAG_OWN_CAR                  307511
FLAG_OWN_REALTY               307511
CNT_CHILDREN                  307511
AMT_INCOME_TOTAL              307511
AMT_CREDIT                    307511
AMT_ANNUITY                   307499
AMT_GOODS_PRICE               307233
NAME_TYPE_SUITE               306219
NAME_INCOME_TYPE              307511
NAME_EDUCATION_TYPE           307511
NAME_FAMILY_STATUS            307511
NAME_HOUSING_TYPE             307511
REGION_POPULATION_RELATIVE    307511
DAYS_BIRTH                    307511
DAYS_EMPLOYED                 307511
DAYS_REGISTRATION             307511
DAYS_ID_PUBLISH               307511
OWN_CAR_AGE                   104582
FLAG_MOBIL                    307511
FLAG_EMP_PHONE                307511
FLAG_WORK_PHONE               307511
FLAG_CONT_MOBILE              307511
FLAG_PHONE                    307511
FLAG_EMAIL                    307511
OCCUPATION_TYPE               211120
CNT_FAM_MEMBERS               307509
                               ...
DEF_30_CNT_SOCIAL_CIRCLE      306490
OBS_60_CNT_SOCIAL_CIRCLE      306490
DEF_60_CNT_SOCIAL_CIRCLE      306490
DAYS_LAST_PHONE_CHANGE        307510
FLAG_DOCUMENT_2               307511
FLAG_DOCUMENT_3               307511
FLAG_DOCUMENT_4               307511
FLAG_DOCUMENT_5               307511
FLAG_DOCUMENT_6               307511
FLAG_DOCUMENT_7               307511
FLAG_DOCUMENT_8               307511
FLAG_DOCUMENT_9               307511
FLAG_DOCUMENT_10              307511
FLAG_DOCUMENT_11              307511
FLAG_DOCUMENT_12              307511
FLAG_DOCUMENT_13              307511
FLAG_DOCUMENT_14              307511
FLAG_DOCUMENT_15              307511
FLAG_DOCUMENT_16              307511
FLAG_DOCUMENT_17              307511
FLAG_DOCUMENT_18              307511
FLAG_DOCUMENT_19              307511
FLAG_DOCUMENT_20              307511
FLAG_DOCUMENT_21              307511
AMT_REQ_CREDIT_BUREAU_HOUR    265992
AMT_REQ_CREDIT_BUREAU_DAY     265992
AMT_REQ_CREDIT_BUREAU_WEEK    265992
AMT_REQ_CREDIT_BUREAU_MON     265992
AMT_REQ_CREDIT_BUREAU_QRT     265992
AMT_REQ_CREDIT_BUREAU_YEAR    265992
Length: 122, dtype: int64

In [17]:
#把有遺失值的欄位列出
appdata_lack_only = appdata[appdata.isnull().values == True]
print(appdata_lack_only)

        SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0           100002       1         Cash loans           M            N
1           100003       0         Cash loans           F            N
1           100003       0         Cash loans           F            N
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
2           100004       0    Revolving loans           M            Y
...            ...     ...                ...         ...          ...
307509      456254       1         Cash loans           F            N
307509      456254       1         Cash loans           F            N
307509      456254       1         Cash loans           F            N
307509      456254       1         Cash loans           F            N
307509      456254       1         Cash loans           F            N
307509      456254       1         Cash loans           F            N
307509      456254       1         Cash loans           F            N
307509      456254       1         Cash loans           F            N
307509      456254       1         Cash loans           F            N
307509      456254       1         Cash loans           F            N
307509      456254       1         Cash loans           F            N
307509      456254       1         Cash loans           F            N
307509      456254       1         Cash loans           F            N
307510      456255       0         Cash loans           F            N
307510      456255       0         Cash loans           F            N
307510      456255       0         Cash loans           F            N
307510      456255       0         Cash loans           F            N
307510      456255       0         Cash loans           F            N
307510      456255       0         Cash loans           F            N
307510      456255       0         Cash loans           F            N
307510      456255       0         Cash loans           F            N
307510      456255       0         Cash loans           F            N
307510      456255       0         Cash loans           F            N
307510      456255       0         Cash loans           F            N
307510      456255       0         Cash loans           F            N
307510      456255       0         Cash loans           F            N
307510      456255       0         Cash loans           F            N
307510      456255       0         Cash loans           F            N
307510      456255       0         Cash loans           F            N
307510      456255       0         Cash loans           F            N

       FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
0                    Y             0          202500.0    406597.5
1                    N             0          270000.0   1293502.5
1                    N             0          270000.0   1293502.5
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
2                    Y             0           67500.0    135000.0
...                ...           ...               ...         ...
307509               Y             0          171000.0    370107.0
307509               Y             0          171000.0    370107.0
307509               Y             0          171000.0    370107.0
307509               Y             0          171000.0    370107.0
307509               Y             0          171000.0    370107.0
307509               Y             0          171000.0    370107.0
307509               Y             0          171000.0    370107.0
307509               Y             0          171000.0    370107.0
307509               Y             0          171000.0    370107.0
307509               Y             0          171000.0    370107.0
307509               Y             0          171000.0    370107.0
307509               Y             0          171000.0    370107.0
307509               Y             0          171000.0    370107.0
307510               N             0          157500.0    675000.0
307510               N             0          157500.0    675000.0
307510               N             0          157500.0    675000.0
307510               N             0          157500.0    675000.0
307510               N             0          157500.0    675000.0
307510               N             0          157500.0    675000.0
307510               N             0          157500.0    675000.0
307510               N             0          157500.0    675000.0
307510               N             0          157500.0    675000.0
307510               N             0          157500.0    675000.0
307510               N             0          157500.0    675000.0
307510               N             0          157500.0    675000.0
307510               N             0          157500.0    675000.0
307510               N             0          157500.0    675000.0
307510               N             0          157500.0    675000.0
307510               N             0          157500.0    675000.0
307510               N             0          157500.0    675000.0

        AMT_ANNUITY             ...              FLAG_DOCUMENT_18  \
0           24700.5             ...                             0
1           35698.5             ...                             0
1           35698.5             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
2            6750.0             ...                             0
...             ...             ...                           ...
307509      20205.0             ...                             0
307509      20205.0             ...                             0
307509      20205.0             ...                             0
307509      20205.0             ...                             0
307509      20205.0             ...                             0
307509      20205.0             ...                             0
307509      20205.0             ...                             0
307509      20205.0             ...                             0
307509      20205.0             ...                             0
307509      20205.0             ...                             0
307509      20205.0             ...                             0
307509      20205.0             ...                             0
307509      20205.0             ...                             0
307510      49117.5             ...                             0
307510      49117.5             ...                             0
307510      49117.5             ...                             0
307510      49117.5             ...                             0
307510      49117.5             ...                             0
307510      49117.5             ...                             0
307510      49117.5             ...                             0
307510      49117.5             ...                             0
307510      49117.5             ...                             0
307510      49117.5             ...                             0
307510      49117.5             ...                             0
307510      49117.5             ...                             0
307510      49117.5             ...                             0
307510      49117.5             ...                             0
307510      49117.5             ...                             0
307510      49117.5             ...                             0
307510      49117.5             ...                             0

       FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0                     0                0                0
1                     0                0                0
1                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
2                     0                0                0
...                 ...              ...              ...
307509                0                0                0
307509                0                0                0
307509                0                0                0
307509                0                0                0
307509                0                0                0
307509                0                0                0
307509                0                0                0
307509                0                0                0
307509                0                0                0
307509                0                0                0
307509                0                0                0
307509                0                0                0
307509                0                0                0
307510                0                0                0
307510                0                0                0
307510                0                0                0
307510                0                0                0
307510                0                0                0
307510                0                0                0
307510                0                0                0
307510                0                0                0
307510                0                0                0
307510                0                0                0
307510                0                0                0
307510                0                0                0
307510                0                0                0
307510                0                0                0
307510                0                0                0
307510                0                0                0
307510                0                0                0

       AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                             0.0                       0.0
1                             0.0                       0.0
1                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
2                             0.0                       0.0
...                           ...                       ...
307509                        0.0                       0.0
307509                        0.0                       0.0
307509                        0.0                       0.0
307509                        0.0                       0.0
307509                        0.0                       0.0
307509                        0.0                       0.0
307509                        0.0                       0.0
307509                        0.0                       0.0
307509                        0.0                       0.0
307509                        0.0                       0.0
307509                        0.0                       0.0
307509                        0.0                       0.0
307509                        0.0                       0.0
307510                        0.0                       0.0
307510                        0.0                       0.0
307510                        0.0                       0.0
307510                        0.0                       0.0
307510                        0.0                       0.0
307510                        0.0                       0.0
307510                        0.0                       0.0
307510                        0.0                       0.0
307510                        0.0                       0.0
307510                        0.0                       0.0
307510                        0.0                       0.0
307510                        0.0                       0.0
307510                        0.0                       0.0
307510                        0.0                       0.0
307510                        0.0                       0.0
307510                        0.0                       0.0
307510                        0.0                       0.0


In [20]:

#一般會刪除有遺失值的觀測row
#appdata_del_lack_row = appdata.dropna(axis=0)

#或是使用上或下一筆資料來填補
#appdata_fill_lack = appdata.fillna(method='ffill')
#appdata_fill_lack = appdata.fillna(method='bfill')

#或是使用平均值或中位數來填補
#appdata_fill_lack = appdata.fillna(appdata.mean())

In [19]:
#檢查有沒有outlier，但這筆資料是每個客戶的狀況，有少數異常狀況比較沒有影響
#可以用常態分配或是四分位數來檢測是否有異常值